# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
# include: 'rules/download_data.smk'
# include: 'rules/simulation.smk'
# include: 'rules/simulate_genotypes.smk'
include: 'rules/single_causal_glm_simulations.smk'

